# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c619cacd-235b-4c7b-8f17-5f6a60705fbb";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c619cacd-235b-4c7b-8f17-5f6a60705fbb".device = "/dev/disk/by-uuid/c619cacd-235b-4c7b-8f17-5f6a60705fbb";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/82E0-EAAF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-2fc53874-8b13-4e3c-82fb-c367815823fb"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
